global:
  environment: "Team-Liran"
  account_id: "<ACCOUNT_ID>"
  region: 'us-east-1'

vpc:
  cidr_block: "192.168.0.0/16"

eks:
  cluster_name: "Team-Liran"
  managed_worker_nodes_nubmer: 0
  unmanaged_worker_nodes_number: 3
  instance_type: 't2.medium'
#  masters_role: "<SOME_ROLE_ARN>"
